export default [
  "Air conditioner",
  "Air fryer",
  "Air ioniser",
  "Blender",
  "Blower",
  "Clothes dryer",
  "Clothes iron",
  "Coffeemaker",
  "Convection oven",
  "Cooker",
  "Cooking plate",
  "Cooking",
  "Cooktop",
  "Crisper drawer",
  "Deep fryer",
  "Dehumidifier",
  "Desktop computer",
  "Dishwasher",
  "Domestic robot",
  "Drying cabinet",
  "Electric blanket",
  "Electric drill",
  "Electric heater",
  "Electric knife",
  "Electric shaver",
  "Electric toothbrush",
  "Electric water boiler",
  "Epilator",
  "Evaporative cooler",
  "Fan heater",
  "Fan",
  "Food processor",
  "Freezer",
  "Furnace",
  "Garbage disposer",
  "Hair dryer",
  "Hair iron",
  "Humidifier",
  "Ice cream maker",
  "Icemaker",
  "Immersion blender",
  "Juicer",
  "Kitchen hood",
  "Kitchen stove",
  "Laptop",
  "Laundry-folding machine",
  "Lawn mower",
  "Lighter",
  "Mechanical Air Ventilator",
  "Microwave oven",
  "Mixer",
  "Oven",
  "Palm Pilot",
  "Pie iron",
  "Pocket PC",
  "Range",
  "Refrigerator",
  "Riding mower",
  "Robotic lawn mower",
  "Sewing machine",
  "Slow cooker",
  "Smartphone",
  "Steamer oven",
  "Stove",
  "Tablet",
  "Television set",
  "Toaster",
  "Ultra-mobile PC",
  "Vacuum cleaner",
  "Waffle iron",
  "Wall oven",
  "Washing machine",
  "Water cooler",
  "Water dispenser",
  "Water heater",
  "Whole house ventilator",
  "Workstation",
];
